//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUD_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETALLES
    {
        public int idDetalle { get; set; }
        public int idFactura { get; set; }
        public int idProducto { get; set; }
        public int Cantidad { get; set; }
        public int PrecioUnitario { get; set; }
    
        public virtual FACTURAS FACTURAS { get; set; }
        public virtual PRODUCTOS PRODUCTOS { get; set; }
    }
}
