//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUD_MVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class FACTURAS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FACTURAS()
        {
            this.DETALLES = new HashSet<DETALLES>();
        }
    
        public int idFactura { get; set; }
        [Required (ErrorMessage = "Campo de código requerido")]
        [Display(Name = "Número de Factura")]
        public int NumeroFactura { get; set; }

        [Required(ErrorMessage = "Campo de fecha requerido")]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}")]
        [Display(Name = "Fecha")]
        public System.DateTime Fecha { get; set; }

        [Required(ErrorMessage = "Campo de tipo de pago requerido")]
        [Display(Name = "Tipo de pago")]   
        public string TipoDePago { get; set; }

        [Required(ErrorMessage = "Campo de documento de cliente requerido")]
        [Display(Name = "Documento de cliente")]
        public long DocumentoCliente { get; set; }

        [Required(ErrorMessage = "Campo de documento de cliente requerido")]
        [Display(Name = "Nombre de cliente")]
        public string NombreCliente { get; set; }
        public decimal SubTotal { get; set; }

        [Required(ErrorMessage = "Campo de Descuento requerido")]
        [Display(Name = "Descuento")]
        public int Descuento { get; set; }

        [Required(ErrorMessage = "Campo de IVA requerido")]
        [Display(Name = "IVA")]
        public int IVA { get; set; }
        public decimal TotalDescuento { get; set; }
        public decimal TotalImpuesto { get; set; }
        public decimal Total { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DETALLES> DETALLES { get; set; }
    }
}
